### ISSUE TITLE
how do I remove "loyal" item drop?

### ISSUE THREAD

**Issue by denny4-user** [Felix14-v2/Loyal-Items#5]
please tell me the command :)

**Comment by Felix14-v2** [comment]
Since 1.0.1 you can use this command:
```
/kill @e[type=item, tag=protected_from_despawn]
```

If you used Loyal Items 1.0.0 previously in your world, you should use this instead:
```
/kill @e[type=item, nbt={Age:-32768}]
```
Keep in mind that the second command filters items by age, which _hypothetically_ may remove custom items from other mods or datapacks if they use the same protection method as in Loyal Items.

Also you won't be able to remove items from unloaded chunks because of the way Minecraft works.
